-- Run this file once in Supabase Dashboard > SQL Editor.
create table if not exists public.properties (
  id bigint generated by default as identity primary key,
  title text not null,
  slug text not null unique,
  code text not null unique,
  type text not null,
  purpose text not null,
  status text not null default 'Available',
  price numeric(14,2) not null,
  city text not null default 'Toronto',
  neighborhood text not null,
  address text not null,
  bedrooms integer not null default 0,
  bathrooms integer not null default 0,
  suites integer not null default 0,
  parking integer not null default 0,
  area numeric(10,2) not null default 0,
  description text not null default '',
  amenities jsonb not null default '[]'::jsonb,
  image text not null default '',
  images jsonb not null default '[]'::jsonb,
  featured boolean not null default false,
  furnished boolean not null default false,
  pets boolean not null default false,
  published boolean not null default false,
  views integer not null default 0,
  seo_title text not null default '',
  seo_description text not null default '',
  video_url text not null default '',
  virtual_tour_url text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  phone text not null,
  property_code text not null default '',
  message text not null,
  preferred_time text not null default '',
  visit_date date,
  status text not null default 'New',
  assignee text not null default 'Lucia Team',
  notes text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  actor text not null,
  action text not null,
  entity_type text not null,
  entity_id text not null,
  details text not null default '',
  created_at timestamptz not null default now()
);

alter table public.properties enable row level security;
alter table public.leads enable row level security;
alter table public.audit_logs enable row level security;

-- Application database access is server-side only through the service role.
-- The browser uses the anonymous key exclusively for Supabase Auth.

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('property-images', 'property-images', true, 8388608, array['image/jpeg','image/png','image/webp','image/avif'])
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;
