import Link from "next/link";
import { notFound } from "next/navigation";
import { SiteFooter, SiteHeader } from "../../../components/SiteChrome";
import { Gallery } from "../../../components/Gallery";
import { LeadForm } from "../../../components/LeadForm";
import { PropertyCard } from "../../../components/PropertyCard";
import { currency, demoProperties } from "../../../lib/demo-data";

export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const{slug}=await params;const p=demoProperties.find(x=>x.slug===slug);return p?{title:`${p.title} | Imobiliária da Lucia`,description:p.description,openGraph:{title:p.title,description:p.description}}:{title:"Property not found"}}
export default async function PropertyDetail({params}:{params:Promise<{slug:string}>}){const{slug}=await params;const p=demoProperties.find(x=>x.slug===slug);if(!p)notFound();const similar=demoProperties.filter(x=>x.id!==p.id&&(x.purpose===p.purpose||x.neighborhood===p.neighborhood)).slice(0,3);const whats=`Hello, I am interested in property ${p.code} – ${p.title}. I would like more information.`;return <><SiteHeader active="Properties"/><main className="detail-page"><div className="container breadcrumbs"><Link href="/">Home</Link> / <Link href="/imoveis">Properties</Link> / {p.title}</div><div className="container"><Gallery images={p.images} title={p.title}/><div className="detail-main"><div className="detail-copy"><div className="detail-title"><div className="eyebrow">{p.type} • {p.purpose} • Ref. {p.code}</div><h1>{p.title}</h1><p className="location">⌖ {p.address}, {p.neighborhood}, {p.city}</p><div className="detail-price">{currency(p.price,p.purpose)}</div></div><div className="detail-specs"><span><b>{p.bedrooms}</b> Bedrooms</span><span><b>{p.bathrooms}</b> Bathrooms</span><span><b>{p.suites}</b> Suites</span><span><b>{p.parking}</b> Parking</span><span><b>{p.area}</b> m²</span></div><h2>About this property</h2><p>{p.description}</p><p>Thoughtful finishes, excellent natural light and a location that makes everyday life easier. Contact us for property taxes, maintenance fees and other listing details.</p><h3>Features and amenities</h3><div className="amenities">{p.amenities.map(a=><span key={a}>✓ {a}</span>)}</div><div className="map-placeholder"><div><b>⌖ {p.neighborhood}, Toronto</b><br/><small>Approximate location shown to protect privacy</small></div></div></div><aside className="detail-sidebar"><div className="interest-card"><h3>Interested in this property?</h3><p>Share your details and speak with a local specialist.</p><LeadForm propertyCode={p.code} compact/><div className="sidebar-actions"><a className="btn btn-action" href={`https://wa.me/14165550148?text=${encodeURIComponent(whats)}`} target="_blank" rel="noreferrer">◉ Chat on WhatsApp</a><a className="btn btn-primary" href="#agendar">Book a showing</a></div></div></aside></div>{similar.length>0&&<section className="similar"><div className="section-heading"><div><div className="section-kicker">YOU MAY ALSO LIKE</div><h2>Similar properties</h2></div></div><div className="property-grid">{similar.map(x=><PropertyCard key={x.id} property={x}/>)}</div></section>}</div></main><SiteFooter/></>}
