import Link from "next/link";
import { notFound } from "next/navigation";
import { SiteFooter, SiteHeader } from "../../../components/SiteChrome";
import { Gallery } from "../../../components/Gallery";
import { LeadForm } from "../../../components/LeadForm";
import { PropertyCard } from "../../../components/PropertyCard";
import { currency, demoProperties } from "../../../lib/demo-data";

export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const{slug}=await params;const p=demoProperties.find(x=>x.slug===slug);return p?{title:`${p.title} | Imobiliária da Lucia`,description:p.description,openGraph:{title:p.title,description:p.description}}:{title:"Imóvel não encontrado"}}
export default async function PropertyDetail({params}:{params:Promise<{slug:string}>}){const{slug}=await params;const p=demoProperties.find(x=>x.slug===slug);if(!p)notFound();const similar=demoProperties.filter(x=>x.id!==p.id&&(x.purpose===p.purpose||x.neighborhood===p.neighborhood)).slice(0,3);const whats=`Olá, tenho interesse no imóvel ${p.code} – ${p.title}. Gostaria de receber mais informações.`;return <><SiteHeader active="Imóveis"/><main className="detail-page"><div className="container breadcrumbs"><Link href="/">Início</Link> / <Link href="/imoveis">Imóveis</Link> / {p.title}</div><div className="container"><Gallery images={p.images} title={p.title}/><div className="detail-main"><div className="detail-copy"><div className="detail-title"><div className="eyebrow">{p.type} • {p.purpose} • Cód. {p.code}</div><h1>{p.title}</h1><p className="location">⌖ {p.address}, {p.neighborhood}, {p.city}</p><div className="detail-price">{currency(p.price,p.purpose)}</div></div><div className="detail-specs"><span><b>{p.bedrooms}</b>Quartos</span><span><b>{p.bathrooms}</b>Banheiros</span><span><b>{p.suites}</b>Suítes</span><span><b>{p.parking}</b>Vagas</span><span><b>{p.area}</b>m²</span></div><h2>Sobre este imóvel</h2><p>{p.description}</p><p>Acabamentos bem escolhidos, excelente iluminação natural e uma localização que facilita a rotina. Entre em contato para consultar impostos, condomínio e demais condições da propriedade.</p><h3>Características e comodidades</h3><div className="amenities">{p.amenities.map(a=><span key={a}>✓ {a}</span>)}</div><div className="map-placeholder"><div><b>⌖ {p.neighborhood}, Toronto</b><br/><small>Localização aproximada para preservar a privacidade</small></div></div></div><aside className="detail-sidebar"><div className="interest-card"><h3>Gostou deste imóvel?</h3><p>Preencha seus dados e fale com um especialista.</p><LeadForm propertyCode={p.code} compact/><div className="sidebar-actions"><a className="btn btn-action" href={`https://wa.me/14165550148?text=${encodeURIComponent(whats)}`} target="_blank" rel="noreferrer">◉ Falar no WhatsApp</a><a className="btn btn-primary" href="#agendar">Agendar visita</a></div></div></aside></div>{similar.length>0&&<section className="similar"><div className="section-heading"><div><div className="section-kicker">VOCÊ TAMBÉM PODE GOSTAR</div><h2>Imóveis semelhantes</h2></div></div><div className="property-grid">{similar.map(x=><PropertyCard key={x.id} property={x}/>)}</div></section>}</div></main><SiteFooter/></>}
