import Link from "next/link";
import { SiteFooter, SiteHeader } from "../components/SiteChrome";
import { HomeSearch } from "../components/HomeSearch";
import { LeadForm } from "../components/LeadForm";
import { PropertyCard } from "../components/PropertyCard";
import { listProperties } from "../lib/properties-db";

export const dynamic = "force-dynamic";
export default async function Home() {
  const properties = await listProperties(false);
  const featured = properties.filter((property) => property.featured).slice(0, 3);
  return <><SiteHeader/><main><section className="hero"><div className="hero-overlay"/><div className="container hero-content"><div className="kicker">YOUR NEXT CHAPTER STARTS HERE</div><h1>More than a property.<br/><em>Your place in Toronto.</em></h1><p>Thoughtful curation, multilingual guidance and confidence at every step of your real estate journey.</p><div className="hero-actions"><Link className="btn btn-accent" href="/imoveis">Search properties</Link><a className="btn btn-outline-light" href="#contato">Contact us</a></div></div><div className="container search-wrap"><HomeSearch/></div></section>
  <section className="section intro" id="sobre"><div className="container split"><div><div className="section-kicker">A CONFIDENT CHOICE</div><h2>Toronto has many addresses.<br/><em>We find yours.</em></h2></div><div><p>For more than 12 years, we have helped families, investors and newcomers make calmer, better-informed real estate decisions.</p><Link className="text-link" href="/imoveis">Explore our selection →</Link></div></div></section>
  <section className="section soft"><div className="container"><div className="section-heading"><div><div className="section-kicker">LUCIA’S CURATED PICKS</div><h2>Featured properties</h2></div><Link className="text-link" href="/imoveis">View all properties →</Link></div><div className="property-grid">{featured.map((p) => <PropertyCard key={p.id} property={p}/>)}</div></div></section>
  <section className="section"><div className="container"><div className="section-heading"><div><div className="section-kicker">FIND IT YOUR WAY</div><h2>Buy or rent in Toronto</h2></div></div><div className="journey-grid"><Link href="/imoveis?purpose=Buy" className="journey-card buy"><span>FOR BUYERS</span><h3>A lasting investment<br/>to call your own.</h3><p>Selected houses, condos and townhouses in Toronto’s best neighbourhoods.</p><b>Explore properties →</b></Link><Link href="/imoveis?purpose=Rent" className="journey-card rent"><span>FOR RENTERS</span><h3>Your next home,<br/>without the hassle.</h3><p>Move-in-ready options with support through every detail of the process.</p><b>View rentals →</b></Link></div></div></section>
  <section className="section neighborhoods"><div className="container"><div className="section-kicker light">NEIGHBOURHOODS WE KNOW WELL</div><h2>Experience Toronto your way.</h2><div className="neighborhood-grid">{[["Yorkville","Urban sophistication","26 properties"],["High Park","Nature and family life","18 properties"],["The Beaches","Life by the lake","14 properties"],["Leslieville","Creativity and community","21 properties"]].map((n,i)=><Link key={n[0]} href={`/imoveis?neighborhood=${n[0]}`} className={`neighborhood n${i}`}><span>{n[2]}</span><h3>{n[0]}</h3><p>{n[1]}</p></Link>)}</div></div></section>
  <section className="section benefits"><div className="container"><div className="section-heading centered"><div><div className="section-kicker">WHY CHOOSE LUCIA</div><h2>Experience that welcomes you.<br/>Knowledge that protects you.</h2></div></div><div className="benefit-grid">{[["01","Personal service","You work with people who listen and understand what truly matters."],["02","Local expertise","A clear understanding of Toronto’s neighbourhoods, prices and opportunities."],["03","From search to keys","Clear guidance through showings, offers, paperwork and negotiation."],["04","Three languages","Service in English, Portuguese and Spanish, with clear communication throughout."]].map(b=><article key={b[0]}><span>{b[0]}</span><h3>{b[1]}</h3><p>{b[2]}</p></article>)}</div></div></section>
  <section className="section testimonials soft"><div className="container"><div className="quote-mark">“</div><blockquote>Lucia made all the difference in our move to Toronto. She explained every step with patience and found a home that truly fits our family.</blockquote><p><b>Mariana & Rafael</b> • Buyers in High Park</p></div></section>
  <section className="section latest"><div className="container"><div className="section-heading"><div><div className="section-kicker">JUST LISTED</div><h2>Recently added</h2></div><Link className="text-link" href="/imoveis?sort=recent">View all →</Link></div><div className="property-grid">{[...properties].sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).slice(0,3).map((p)=><PropertyCard key={p.id} property={p}/>)}</div></div></section>
  <section className="contact-section"><div className="container contact-grid"><div><div className="section-kicker light">LET’S TALK</div><h2>Tell us what you are looking for.</h2><p>A no-pressure conversation can be the first step toward finding the right property in Toronto.</p><a className="contact-phone" href="tel:+14165550148">+1 (416) 555-0148</a></div><div className="contact-card"><h3>Talk to our team</h3><LeadForm compact/></div></div></section></main><SiteFooter/></>;
}
