import Link from "next/link";
import { SiteFooter, SiteHeader } from "../components/SiteChrome";
import { HomeSearch } from "../components/HomeSearch";
import { LeadForm } from "../components/LeadForm";
import { PropertyCard } from "../components/PropertyCard";
import { demoProperties } from "../lib/demo-data";

export default function Home() {
  const featured = demoProperties.filter((p) => p.featured);
  return <><SiteHeader/><main><section className="hero"><div className="hero-overlay"/><div className="container hero-content"><div className="kicker">SEU NOVO CAPÍTULO COMEÇA AQUI</div><h1>Mais que um imóvel.<br/><em>O seu lugar em Toronto.</em></h1><p>Curadoria cuidadosa, orientação em português e confiança em cada etapa da sua jornada imobiliária.</p><div className="hero-actions"><Link className="btn btn-accent" href="/imoveis">Buscar imóveis</Link><a className="btn btn-outline-light" href="#contato">Fale conosco</a></div></div><div className="container search-wrap"><HomeSearch/></div></section>
  <section className="section intro" id="sobre"><div className="container split"><div><div className="section-kicker">UMA ESCOLHA SEGURA</div><h2>Toronto tem muitos endereços.<br/><em>Nós encontramos o seu.</em></h2></div><div><p>Há mais de 12 anos, ajudamos famílias, investidores e recém-chegados a tomar decisões imobiliárias mais tranquilas e bem-informadas.</p><Link className="text-link" href="/imoveis">Conheça nossa seleção →</Link></div></div></section>
  <section className="section soft"><div className="container"><div className="section-heading"><div><div className="section-kicker">CURADORIA DA LUCIA</div><h2>Imóveis em destaque</h2></div><Link className="text-link" href="/imoveis">Ver todos os imóveis →</Link></div><div className="property-grid">{featured.map((p) => <PropertyCard key={p.id} property={p}/>)}</div></div></section>
  <section className="section"><div className="container"><div className="section-heading"><div><div className="section-kicker">ENCONTRE DO SEU JEITO</div><h2>Comprar ou alugar em Toronto</h2></div></div><div className="journey-grid"><Link href="/imoveis?purpose=Compra" className="journey-card buy"><span>PARA COMPRAR</span><h3>Um patrimônio<br/>para chamar de seu.</h3><p>Casas, condos e townhouses selecionados nos melhores bairros.</p><b>Explorar imóveis →</b></Link><Link href="/imoveis?purpose=Aluguel" className="journey-card rent"><span>PARA ALUGAR</span><h3>Seu próximo lar,<br/>sem complicação.</h3><p>Opções prontas para morar, com apoio em cada detalhe do processo.</p><b>Ver opções →</b></Link></div></div></section>
  <section className="section neighborhoods"><div className="container"><div className="section-kicker light">REGIÕES QUE CONHECEMOS DE PERTO</div><h2>Viva Toronto do seu jeito.</h2><div className="neighborhood-grid">{[["Yorkville","Sofisticação urbana","26 imóveis"],["High Park","Natureza e família","18 imóveis"],["The Beaches","Vida perto do lago","14 imóveis"],["Leslieville","Criatividade e comunidade","21 imóveis"]].map((n,i)=><Link key={n[0]} href={`/imoveis?neighborhood=${n[0]}`} className={`neighborhood n${i}`}><span>{n[2]}</span><h3>{n[0]}</h3><p>{n[1]}</p></Link>)}</div></div></section>
  <section className="section benefits"><div className="container"><div className="section-heading centered"><div><div className="section-kicker">POR QUE A LUCIA</div><h2>Experiência que acolhe.<br/>Conhecimento que protege.</h2></div></div><div className="benefit-grid">{[["01","Atendimento humano","Você fala com pessoas que escutam e entendem o que realmente importa."],["02","Conhecimento local","Leitura precisa dos bairros, preços e oportunidades de Toronto."],["03","Do início às chaves","Acompanhamento claro em visitas, propostas, documentos e negociação."],["04","Três idiomas","Atendimento em português, inglês e espanhol, sem ruídos no caminho."]].map(b=><article key={b[0]}><span>{b[0]}</span><h3>{b[1]}</h3><p>{b[2]}</p></article>)}</div></div></section>
  <section className="section testimonials soft"><div className="container"><div className="quote-mark">“</div><blockquote>A Lucia fez toda a diferença na nossa mudança para Toronto. Explicou cada etapa com paciência e encontrou uma casa que realmente combina com a nossa família.</blockquote><p><b>Mariana & Rafael</b> • Compradores em High Park</p></div></section>
  <section className="section latest"><div className="container"><div className="section-heading"><div><div className="section-kicker">NOVIDADES</div><h2>Adicionados recentemente</h2></div><Link className="text-link" href="/imoveis?sort=recent">Ver todos →</Link></div><div className="property-grid">{demoProperties.slice(-3).reverse().map((p)=><PropertyCard key={p.id} property={p}/>)}</div></div></section>
  <section className="contact-section"><div className="container contact-grid"><div><div className="section-kicker light">VAMOS CONVERSAR?</div><h2>Conte para nós o que você procura.</h2><p>Uma conversa sem compromisso pode ser o primeiro passo para encontrar o imóvel certo em Toronto.</p><a className="contact-phone" href="tel:+14165550148">+1 (416) 555-0148</a></div><div className="contact-card"><h3>Fale com nossa equipe</h3><LeadForm compact/></div></div></section></main><SiteFooter/></>;
}
