import { sql } from "drizzle-orm";
import { integer, real, sqliteTable, text } from "drizzle-orm/sqlite-core";

export const properties = sqliteTable("properties", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  title: text("title").notNull(),
  slug: text("slug").notNull().unique(),
  code: text("code").notNull().unique(),
  type: text("type").notNull(),
  purpose: text("purpose").notNull(),
  status: text("status").notNull().default("Disponível"),
  price: real("price").notNull(),
  city: text("city").notNull().default("Toronto"),
  neighborhood: text("neighborhood").notNull(),
  address: text("address").notNull(),
  bedrooms: integer("bedrooms").notNull().default(0),
  bathrooms: integer("bathrooms").notNull().default(0),
  suites: integer("suites").notNull().default(0),
  parking: integer("parking").notNull().default(0),
  area: real("area").notNull().default(0),
  description: text("description").notNull().default(""),
  amenities: text("amenities").notNull().default("[]"),
  image: text("image").notNull().default(""),
  images: text("images").notNull().default("[]"),
  featured: integer("featured", { mode: "boolean" }).notNull().default(false),
  furnished: integer("furnished", { mode: "boolean" }).notNull().default(false),
  pets: integer("pets", { mode: "boolean" }).notNull().default(false),
  published: integer("published", { mode: "boolean" }).notNull().default(false),
  views: integer("views").notNull().default(0),
  seoTitle: text("seo_title").notNull().default(""),
  seoDescription: text("seo_description").notNull().default(""),
  videoUrl: text("video_url").notNull().default(""),
  virtualTourUrl: text("virtual_tour_url").notNull().default(""),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const leads = sqliteTable("leads", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  name: text("name").notNull(),
  email: text("email").notNull(),
  phone: text("phone").notNull(),
  propertyCode: text("property_code").notNull().default(""),
  message: text("message").notNull(),
  preferredTime: text("preferred_time").notNull().default(""),
  visitDate: text("visit_date").notNull().default(""),
  status: text("status").notNull().default("Novo"),
  assignee: text("assignee").notNull().default("Equipe Lucia"),
  notes: text("notes").notNull().default(""),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const auditLogs = sqliteTable("audit_logs", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  actor: text("actor").notNull(),
  action: text("action").notNull(),
  entityType: text("entity_type").notNull(),
  entityId: text("entity_id").notNull(),
  details: text("details").notNull().default(""),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});
